Registro
static establecerConexion()
static devolverDatos($preparada, $consulta)
Busca y devuelve los datos que se le piden a la bbdd string $preparada array $consulta boolean | array false si no se puede realizar la operación o un array con los datos
Referenced by buscarInvitado, devolverUsuario.
static operarCommit($preparada, $consulta)
Realiza diversas operaciones(insert, select, update) sobre una tabla. string $preparada array $consulta boolean verdadero o falso según se complete o no la operación
static operarCommitDoble($preparada, $preparadaP, $consulta, $consultaP)
Realiza diversas operaciones(insert, select, update) sobre la base de datos. Actúa sobre dos tablas relacionadas, biologos y personas, invitados y personas, especimenes y especies... string $preparada la select a llevar a cabo en la primera tabla string $preparadaP la select a llevar a cabo en la segunda tabla array $consulta la consulta sobre la select en la primera tabla array $consultaP la consulta sobre la select en la segunda tabla boolean verdadero o falso según se complete o no la operación
static buscarInvitado($usuario, $mail)
Función de acceso público, comprueba si existe el usuario en la tabla 'usuarios' a través del usuario y el mail, los cuales han de ser únicos. Comunica si el usuario o el mail están en uso con un mensaje y devuelve una excepción si se produce algún error. ****Solo se usa para registrar invitados string $usuario string $mail boolean
References devolverDatos.
static insertarInvitado($consulta, $consultaP)
****Solo se usa para registrar invitados Tiene que sacar el id del invitado y el commit tiene que ser completo array $consulta array $consultaP boolean
static verificarClave($consulta, $clave)
Función para verificar si la clave introducida corresponde con el usuario introducido string $consulta puede ser mail, dni o nombre de usuario string $clave de acceso al sitio web boolean si la contraseña es correcta o falsa
References Validar\dni, Validar\mail, Validar\usuario.
Referenced by comprobarClave.
static devolverUsuario($tabla, $tipoLogin, $consulta)
Función para crear un objeto con los datos rescatados de la BBDD string $tabla en la que buscar los datos ('biologos' o 'invitados') string $tipoLogin indica si es 'dni', 'mail' o 'usuario' array $consulta el dato a consultar boolean|\Biologo|\Invitado falso o el objeto creado
References devolverDatos.
Referenced by comprobarClave.