Validar
static camposTexto($variable)
Limpia los campos de texto de cualqiuer caracter extraño y elimina los espacios en blanco al principio y al final string $variable contiene el dato a limpiar boolean el dato o false si el campo está vacío
Referenced by clave, codigoE, comprobarCodigo, dimensiones, direccion, dni, especie, fecha, mail, migracion, nombre, peso, provincia, telefono, usuario.
static nombre($variable)
Valida que el dato nombre y apellido encajen en un patrón type $variable el dato a validar boolean el nombre o false si no encaja en el patrón
References camposTexto.
static usuario($variable)
Valida que el dato usuario encaje en un patrón. No puede empezar por un número y debe constar de al menos 3 caracteres, los dos primeros letras. type $variable el dato a validar boolean el nombre de usuario o false si no encaja en el patrón
References camposTexto.
Referenced by Registro\verificarClave.
static dni($variable)
Valida que el número del DNI encaja en un patrón y comprueba que es un dni real string $variable NIF completo boolean false o el número si es verdadero
References camposTexto.
Referenced by Registro\verificarClave.
static mail($variable)
Valida que el mail introducido pueda ser correcto string $variable mail boolean el mail o false si no es correcto
References camposTexto.
Referenced by Registro\verificarClave.
static telefono($variable)
Valida que el teléfono introducido pueda se correcto, para lo cual debe empezar por 9, 8, 7 o 6 string $variable número de teléfono boolean el dato o false si no es verdadero
References camposTexto.
static direccion($variable)
Valida que la dirección introducida corresponda con un patrón válido y el campo no esté vacio string $variable le dirección boolean la dirección o false si no es correcto
References camposTexto.
static provincia($variable)
Valida que la provincia sea correcta y no esté en blanco string $variable provincia boolean el campo o false en caso de no ser correcto
References camposTexto.
static fecha($variable)
Verifica qu ela fecha responde a un patrón válido y en ese caso comprueba que la fecha corresponda con un día y mes acordes y que la fecha introducida no sea mayor que la fecha actual string $variable la fecha introducida boolean verdadero si la fecha es correcta y falso si no lo es
References camposTexto.
static clave($variable)
Verifica que la clave introducida responda a un patrón válido string $variable la clave introducida boolean la clave o falso si no es correcta
References camposTexto.
static especie($variable)
Verifica que la especie introducida responda a un patrón válido string $variable boolean
References camposTexto.
static migracion($variable)
Verifica que el periodo migratorio introducido responda a un patrón válido string $variable boolean
References camposTexto.
static codigoE($variable)
Verifica que el código de especie introducido responda a un patrón válido string $variable boolean
References camposTexto.
static peso($variable)
Verifica que el peso introducido responda a un patrón válido string $variable boolean
References camposTexto.
static dimensiones($variable)
Verifica que las dimensiones introducidas respondan a un patrón válido string $variable boolean
References camposTexto.
static letraDni($numero, $letra)
Función privada para validar que la letra del DNI es correcta int $numero del DNI string $letra del DNI boolean
static esCorrectaFecha($dia, $mes, $anno)
static esCorrectoDia($anno, $mes, $dia)