.TH "G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/comprobarCodigo.php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/comprobarCodigo.php
.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBcomprobarCodigo\fP ($variable)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "comprobarCodigo ( $variable)"
Proyecto Parque Eocológico
.PP
\fBVersión\fP
.RS 4
pq-_V18 @autor Virginia M\&. García Álvarez Comprueba que el código para el registro de biólogos es correcto\&.
.RE
.PP
\fBParámetros\fP
.RS 4
\fI$variable\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
string 
.RE
.PP

.PP
Definición en la línea \fB19\fP del archivo \fBcomprobarCodigo\&.php\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
