.TH "Especimenes" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Especimenes
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBEspecie\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($codigoRegistro, $registrador, $especie, $peso, $dimensiones, $caracteristicas, $fechaRegistro)"
.br
.ti -1c
.RI "\fBagregarEspecie\fP ($especie, $reino, $clase, $orden, $familia, $periodoMigratorio)"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Proyecto Parque Eocológico
.PP
\fBVersión\fP
.RS 4
pq-_V18 @autor Virginia M\&. García Álvarez Clase para crear Epecímenes, hereda de \fBEspecie\fP 
.RE
.PP

.PP
Definición en la línea \fB14\fP del archivo \fBEspecimen\&.php\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "__construct ( $codigoRegistro,  $registrador,  $especie,  $peso,  $dimensiones,  $caracteristicas,  $fechaRegistro)"
Constructor de siete parámetros
.PP
\fBParámetros\fP
.RS 4
\fI$codigoRegistro\fP 
.br
\fI$registrador\fP 
.br
\fI$especie\fP 
.br
\fI$peso\fP 
.br
\fI$dimensiones\fP 
.br
\fI$caracteristicas\fP 
.br
\fI$fechaRegistro\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
Especimen 
.RE
.PP

.PP
Definición en la línea \fB57\fP del archivo \fBEspecimen\&.php\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "agregarEspecie ( $especie,  $reino,  $clase,  $orden,  $familia,  $periodoMigratorio)"
Agrega especie cuando no ha sido creada previamente, y porque todo especímen pertenece a una especie\&. Recibe 6 parámetros
.PP
\fBParámetros\fP
.RS 4
\fI$especie\fP 
.br
\fI$reino\fP 
.br
\fI$clase\fP 
.br
\fI$orden\fP 
.br
\fI$familia\fP 
.br
\fI$periodoMigratorio\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
void 
.RE
.PP

.PP
Reimplementado de \fBEspecie\fP\&.
.PP
Definición en la línea \fB79\fP del archivo \fBEspecimen\&.php\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
