.TH "Referencia del directorio G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBclasesPHP\fP"
.br
.in -1c
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBcomprobarCodigo\&.php\fP"
.br
.ti -1c
.RI "archivo \fBlogin\&.php\fP"
.br
.ti -1c
.RI "archivo \fBmodificarDatos copy\&.php\fP"
.br
.ti -1c
.RI "archivo \fBmodificarDatos\&.php\fP"
.br
.ti -1c
.RI "archivo \fBoperacionesBiologos\&.php\fP"
.br
.ti -1c
.RI "archivo \fBoperacionesInvitados\&.php\fP"
.br
.ti -1c
.RI "archivo \fBrecogerUsuario\&.php\fP"
.br
.ti -1c
.RI "archivo \fBredirecciones\&.php\fP"
.br
.ti -1c
.RI "archivo \fBregistrarse\&.php\fP"
.br
.ti -1c
.RI "archivo \fBsalir\&.php\fP"
.br
.ti -1c
.RI "archivo \fBsesionActiva\&.php\fP"
.br
.ti -1c
.RI "archivo \fBtiempo\&.php\fP"
.br
.ti -1c
.RI "archivo \fBusuarios\&.php\fP"
.br
.in -1c
