.TH "Referencia del directorio G:/xamppVZ/htdocs" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio G:/xamppVZ/htdocs
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fB000_TAREA_CONJUNTA\fP"
.br
.in -1c
