.TH "Referencia del directorio G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/clasesPHP" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/clasesPHP
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBespecies\fP"
.br
.ti -1c
.RI "directorio \fBpersona\fP"
.br
.in -1c
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBRegistro\&.php\fP"
.br
.ti -1c
.RI "archivo \fBValidar\&.php\fP"
.br
.in -1c
