.TH "Referencia del directorio G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/clasesPHP/especies" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/clasesPHP/especies
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBEspecie\&.php\fP"
.br
.ti -1c
.RI "archivo \fBEspecimen\&.php\fP"
.br
.ti -1c
.RI "archivo \fBTorreta\&.php\fP"
.br
.in -1c
