.TH "G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/login.php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/login.php
.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBcomprobarClave\fP ($usuario, $clave, $tipoLogin, $tipoUsuario)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "comprobarClave ( $usuario,  $clave,  $tipoLogin,  $tipoUsuario)"
Función para verificar la clave y crear las variables de la sesión
.PP
\fBParámetros\fP
.RS 4
\fI$usuario\fP dni, mail o nombre de usuario 
.br
\fI$clave\fP clave de acceso 
.br
\fI$tipoLogin\fP indica si es el dato $usuario será un dni, mail o nombre de usuario 
.br
\fI$tipoUsuario\fP indica si es 'biologos' o 'invitados' 
.RE
.PP

.PP
Definición en la línea \fB24\fP del archivo \fBlogin\&.php\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
