.TH "G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/redirecciones.php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/redirecciones.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "if(count($_SESSION) !=0) \fBelse\fP"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "if (count( $_SESSION) !=0) else"
\fBValor inicial:\fP
.PP
.nf
{
        
        
        header('Location:' \&. getenv('HTTP_REFERER'))
.fi
.PP
Definición en la línea \fB30\fP del archivo \fBredirecciones\&.php\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
