.TH "G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/salir.php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/salir.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$navegadorUsuario\fP = strtoupper($_SERVER['HTTP_USER_AGENT'])"
.br
.ti -1c
.RI "\fB$firefox\fP = 'FIREFOX'"
.br
.ti -1c
.RI "\fB$encontrado\fP = strpos($firefox, $navegadorUsuario)"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "$encontrado = strpos($firefox, $navegadorUsuario)"

.PP
Definición en la línea \fB14\fP del archivo \fBsalir\&.php\fP\&.
.SS "$firefox = 'FIREFOX'"

.PP
Definición en la línea \fB13\fP del archivo \fBsalir\&.php\fP\&.
.SS "$navegadorUsuario = strtoupper($_SERVER['HTTP_USER_AGENT'])"

.PP
Definición en la línea \fB12\fP del archivo \fBsalir\&.php\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
