.TH "G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/sesionActiva.php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/sesionActiva.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "if(count($_SESSION) !=0 &&array_key_exists('tipoLogin', $_SESSION)) \fBelse\fP"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "if (count( $_SESSION) !=0 &&array_key_exists( 'tipoLogin', $_SESSION)) else"
\fBValor inicial:\fP
.PP
.nf
{
        echo 'false'
.fi
.PP
Definición en la línea \fB17\fP del archivo \fBsesionActiva\&.php\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
