.TH "G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/tiempo.php" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/xamppVZ/htdocs/000_TAREA_CONJUNTA/ParqueEcologicoBoostrap_V18/php/tiempo.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$apiKeyT\fP = 'cbc35f2e21aeb553bcc014213b8791d6'"
.br
.ti -1c
.RI "\fB$cityId\fP = '3105971'"
.br
.ti -1c
.RI "\fB$googleApiUrl\fP = 'http://api\&.openweathermap\&.org/data/2\&.5/weather?id=' \&. $cityId \&. '&lang=es&units=metric&APPID=' \&. $apiKeyT"
.br
.ti -1c
.RI "\fB$ch\fP = curl_init()"
.br
.ti -1c
.RI "\fB$response\fP = curl_exec($ch)"
.br
.in -1c
.SH "Documentación de las variables"
.PP 
.SS "$apiKeyT = 'cbc35f2e21aeb553bcc014213b8791d6'"
Proyecto Parque Eocológico
.PP
\fBVersión\fP
.RS 4
pq-_V18 @autor Virginia M\&. García Álvarez 
.RE
.PP

.PP
Definición en la línea \fB11\fP del archivo \fBtiempo\&.php\fP\&.
.SS "$ch = curl_init()"

.PP
Definición en la línea \fB16\fP del archivo \fBtiempo\&.php\fP\&.
.SS "$cityId = '3105971'"

.PP
Definición en la línea \fB12\fP del archivo \fBtiempo\&.php\fP\&.
.SS "$googleApiUrl = 'http://api\&.openweathermap\&.org/data/2\&.5/weather?id=' \&. $cityId \&. '&lang=es&units=metric&APPID=' \&. $apiKeyT"

.PP
Definición en la línea \fB14\fP del archivo \fBtiempo\&.php\fP\&.
.SS "$response = curl_exec($ch)"

.PP
Definición en la línea \fB24\fP del archivo \fBtiempo\&.php\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
