.TH "Torreta" 3 "Viernes, 20 de Mayo de 2022" "Version V18" "Parque Ecológico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Torreta
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBgetIdTorreta\fP ()"
.br
.ti -1c
.RI "\fBgetChip\fP ()"
.br
.ti -1c
.RI "\fBgetFechasEntrada\fP ()"
.br
.ti -1c
.RI "\fBgetFechasSalida\fP ()"
.br
.ti -1c
.RI "\fBagregarFechaEntrada\fP ($fecha)"
.br
.ti -1c
.RI "\fBagregarFechaSalida\fP ($fecha)"
.br
.ti -1c
.RI "\fBrecogerChip\fP ($chip)"
.br
.ti -1c
.RI "\fBidentificarTorreta\fP ($idTorreta)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Proyecto Parque Eocológico
.PP
\fBVersión\fP
.RS 4
pq-_V18 @autor Virginia M\&. García Álvarez 
.RE
.PP
\fBVer también\fP
.RS 4
class Especimen 
.RE
.PP

.PP
Definición en la línea \fB16\fP del archivo \fBTorreta\&.php\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "agregarFechaEntrada ( $fecha)"
Agrega una fecha de entrada al array de fechas de entrada
.PP
\fBParámetros\fP
.RS 4
\fI$fecha\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
void 
.RE
.PP

.PP
Definición en la línea \fB72\fP del archivo \fBTorreta\&.php\fP\&.
.SS "agregarFechaSalida ( $fecha)"
Agrega una fecha de salida al array de fechas de salida
.PP
\fBParámetros\fP
.RS 4
\fI$fecha\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
void 
.RE
.PP

.PP
Definición en la línea \fB82\fP del archivo \fBTorreta\&.php\fP\&.
.SS "getChip ()"
Muestra el número de registro del especimen
.PP
\fBDevuelve\fP
.RS 4
string 
.RE
.PP

.PP
Definición en la línea \fB46\fP del archivo \fBTorreta\&.php\fP\&.
.SS "getFechasEntrada ()"
Muestra el registro de las fechas de entrada del especimen
.PP
\fBDevuelve\fP
.RS 4
string 
.RE
.PP

.PP
Definición en la línea \fB54\fP del archivo \fBTorreta\&.php\fP\&.
.SS "getFechasSalida ()"
Muestra el registro de las fechas de salida del especimen
.PP
\fBDevuelve\fP
.RS 4
string 
.RE
.PP

.PP
Definición en la línea \fB62\fP del archivo \fBTorreta\&.php\fP\&.
.SS "getIdTorreta ()"
Muestra el id de la \fBTorreta\fP
.PP
\fBDevuelve\fP
.RS 4
string 
.RE
.PP

.PP
Definición en la línea \fB38\fP del archivo \fBTorreta\&.php\fP\&.
.SS "identificarTorreta ( $idTorreta)"
Identifica la \fBTorreta\fP en uso
.PP
\fBParámetros\fP
.RS 4
\fI$idTorreta\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
void 
.RE
.PP

.PP
Definición en la línea \fB102\fP del archivo \fBTorreta\&.php\fP\&.
.SS "recogerChip ( $chip)"
Recoge el número de registro de un especimen
.PP
\fBParámetros\fP
.RS 4
\fI$fecha\fP 
.RE
.PP
\fBDevuelve\fP
.RS 4
void 
.RE
.PP

.PP
Definición en la línea \fB92\fP del archivo \fBTorreta\&.php\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Parque Ecológico del código fuente\&.
